from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from app_venin_web_new1.views import *
urlpatterns = [
    path('auth/login/',LoginView.as_view(), name='auth_login'),
    path('auth/logout/',LogoutView.as_view(), name='auth_logout'),
    path('empresa', EmpresaView.as_view()),
    path('empresa/<int:pk>/', EmpresaDetails.as_view()),
    path('sucursal/', SucursalView.as_view()),
    path('sucursal/<str:pk>/', SucursalDetail.as_view()),
    path('search_personal/', SearchPersonalView.as_view()), 
    path('personal/<int:pk>/', PersonalDetails.as_view()),
    path('personal/<str:option>/<str:pk>/', PersonalDetails.as_view()),
    path('personal/', PersonalView.as_view()), 
    path('cajaefectivo/<str:option>/<str:pk>/', PersonalDetails.as_view()),
    path('cliente/', ClienteView.as_view()),
    path('search_cliente/', ClienteSearchAPIView.as_view()),
    path('cliente/<int:pk>/', ClienteDetails.as_view()),
    path('transportista/', TransportistaView.as_view()),
    path('transportista/<int:pk>/', TransportistaDetails.as_view()),
    path('search_transportista/', TransportistaSearchAPIView.as_view()),
    path('detallepago/', DetallePagoView.as_view()),
    path('detallepago/<int:pk>/', DetallePagoDetails.as_view()),
    path('guia_salida/', GuiaSalidaView.as_view()),
    path('guia_salida/<int:pk>/', GuiaSalidaDetails.as_view()),
    path('guia_salida_completa/', GuiaSalidaCompletaView.as_view()),
    path('guia_salida_completa/<int:id>/', GuiaSalidaCompletaView.as_view()),
    path('search_guiasalida/', GuiaSalidaSearchAPIView.as_view()),
    path('articulos/', ArticulosView.as_view()),
    path('articulos/<int:pk>/', ArticulosDetails.as_view()),
    path('tarjetacre/', TarjetaCreView.as_view()),
    path('search_articulos/', ArticulosSearchAPIView.as_view()),
    path('ajuste/', AjusteView.as_view()),
    path('ajuste/<int:pk>/', AjusteDetails.as_view()),
    path('search_ajuste/', AjusteSearchAPIView.as_view()),
    path('detajuste/', DetajusteView.as_view()),
    path('detajuste/<int:pk>/', DetajusteDetails.as_view()),
    path('detguia/', DetguiaView.as_view()),
    path('detguia/<int:pk>/', DetguiaView.as_view()),
    path('detalleguia/', DetalleGuiaView.as_view()),
    path('detalleguia/<int:pk>/', DetalleGuiaView.as_view()),
    path('dashboard/', DashboardApiView.as_view()),
    path('kardex/', KardexAPIView.as_view(), name='kardex'),
    path('excel/kardex', KardexExportXLSXAPIView.as_view(), name='kardex_excel'),
    path('excel/cuenta_cliente', CuentaPersonalExcelAPIView.as_view(), name='cuenta_cliente_excel'),
    path('excel/planilla_mov', PlanillaMovimientosExcelAPIView.as_view(), name='planilla_mov_excel'),
    path('excel/metodo_pago', CuentaDetallePagoExcelAPIView.as_view(), name='metodo_pago_excel'),
    path('download_excel/<filename>', download_excel_view, name='download_excel'),
    path("delete_excel/<filename>",eliminar_excel),
    # path('kardexval/', views.KardexValoradoAPIView.as_view(), name='kardex'),
    # path('kardexgeneral/', views.KardexGeneralAPIView.as_view(), name='kardex'),
    path('cuenta_cliente/', CuentaPersonalAPIView.as_view()),
    path('metodo_pago/', CuentaDetallePagoAPIView.as_view()),
    path('planilla_mov/', PlanillaMovimientosAPIView.as_view())
    
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)