# Generated by Django 4.1 on 2025-09-13 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('idajuste', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'ajuste',
            },
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('idproduct', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=25, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'articulos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('tipodoc', models.CharField(blank=True, max_length=1, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(primary_key=True, serialize=False)),
                ('razonsocial', models.CharField(blank=True, max_length=100, null=True)),
                ('ruc', models.CharField(blank=True, max_length=11, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('nombrecomercial', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('logotipo', models.CharField(blank=True, max_length=150, null=True)),
                ('dominio', models.CharField(blank=True, max_length=100, null=True)),
                ('codigofis', models.CharField(blank=True, max_length=4, null=True)),
                ('codigoubigeo', models.CharField(blank=True, max_length=6, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('current_sucursal_dir', models.CharField(blank=True, max_length=300, null=True)),
                ('dtr_bconac', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, upload_to='logos/')),
                ('logo2', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo3', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('observacion', models.CharField(blank=True, max_length=100, null=True)),
                ('refran', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('cuenta', models.CharField(blank=True, max_length=20, null=True)),
                ('cci', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('idtrans', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'transportista',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idsucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=70, null=True)),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('empresa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app_venin_web_new1.empresa')),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('idpersonal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('direccion', models.CharField(blank=True, max_length=40, null=True)),
                ('tipodocumento', models.CharField(blank=True, max_length=1, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('notas', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.CharField(blank=True, max_length=3, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.CharField(blank=True, default='1', max_length=1, null=True)),
                ('nivel_usuario', models.CharField(choices=[('1', 'Administrador'), ('2', 'Usuario')], default='1', max_length=1)),
                ('idsucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venin_web_new1.sucursal')),
                ('idusuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personal',
            },
        ),
        migrations.CreateModel(
            name='GuiaSalida',
            fields=[
                ('idguiar', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('hora', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('estado', models.CharField(blank=True, max_length=3, null=True)),
                ('referencia', models.CharField(blank=True, max_length=40, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venin_web_new1.cliente')),
                ('idsucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venin_web_new1.sucursal')),
                ('idtransporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venin_web_new1.transportista')),
            ],
        ),
        migrations.CreateModel(
            name='Detguia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('idguiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_venin_web_new1.guiasalida')),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venin_web_new1.articulos')),
            ],
            options={
                'db_table': 'detguia',
            },
        ),
        migrations.CreateModel(
            name='DetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaPago', models.DateField(blank=True, null=True)),
                ('referencias', models.CharField(blank=True, max_length=20, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('idguiar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_venin_web_new1.guiasalida')),
            ],
            options={
                'db_table': 'detallepago',
            },
        ),
        migrations.CreateModel(
            name='Detajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('idajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_venin_web_new1.ajuste')),
                ('idproduct', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venin_web_new1.articulos')),
            ],
            options={
                'db_table': 'detajuste',
            },
        ),
        migrations.AddField(
            model_name='ajuste',
            name='idsuscursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_venin_web_new1.sucursal'),
        ),
    ]
