# Generated by Django 4.1 on 2025-09-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_venin_web_new1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guiasalida',
            table='guiasalida',
        ),
    ]
