# Generated by Django 4.1 on 2025-09-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_venin_web_new1', '0002_alter_guiasalida_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajuste',
            name='idsuscursal',
        ),
        migrations.AddField(
            model_name='ajuste',
            name='idsucursal',
            field=models.ForeignKey(db_column='idsucursal', default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_venin_web_new1.sucursal'),
        ),
    ]
