# Generated by Django 4.1 on 2025-09-23 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_venin_web_new1', '0003_remove_ajuste_idsuscursal_ajuste_idsucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuste',
            name='idsucursal',
            field=models.ForeignKey(db_column='idsucursal', on_delete=django.db.models.deletion.PROTECT, to='app_venin_web_new1.sucursal'),
        ),
    ]
