# Generated by Django 4.1 on 2025-09-23 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_venin_web_new1', '0004_alter_ajuste_idsucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detajuste',
            name='idajuste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_venin_web_new1.ajuste'),
        ),
    ]
