# Generated by Django 4.1 on 2025-09-24 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_venin_web_new1', '0005_alter_detajuste_idajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
