# Generated by Django 4.1 on 2025-09-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_venin_web_new1', '0006_articulos_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulos',
            old_name='saldo',
            new_name='saldo00001',
        ),
        migrations.AddField(
            model_name='articulos',
            name='saldo00002',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
