# Generated by Django 4.1 on 2025-09-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_venin_web_new1', '0007_rename_saldo_articulos_saldo00001_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'tarjetacre',
            },
        ),
        migrations.AddField(
            model_name='detallepago',
            name='tipo_pago',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
